"""empty message

Revision ID: 435f2f99415
Revises: None
Create Date: 2015-07-24 18:53:50.132800

"""

# revision identifiers, used by Alembic.
revision = '435f2f99415'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('max_characters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('tile',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('background_image', sa.String(length=32), nullable=True),
    sa.Column('background_colour', sa.String(length=7), nullable=True),
    sa.Column('css_class', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('tile_id')
    )
    op.create_table('account_auth',
    sa.Column('account_auth_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('account_auth_id')
    )
    op.create_table('character',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.String(length=10), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('world', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=True)
    op.create_table('map',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('world', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('css_class', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.tile_id'], ),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_table('account_auth_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_auth_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_auth_id'], ['account_auth.account_auth_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_auth_local')
    op.drop_table('map')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_table('character')
    op.drop_table('account_auth')
    op.drop_table('tile')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    ### end Alembic commands ###
